version: '2.0'
services:
  server:
    image: romachron-server
    build:
      context: ./server
    ports:
      - '8080:8080'
  frontend:
    image: romachron-ui
    build:
      context: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - server