version: '3.8'
services:
  server:
    build:
      context: ./server
    ports:
      - '8080:8080'
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - server