version: '3'
services:
  server:
    image: bucrogers26th/romachron-server:stable
    build:
      context: ./server
    ports:
      - '8080:8080'
  frontend:
    image: bucrogers26th/romachron-ui:stable
    build:
      context: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - server